### ISSUE TITLE
Center align text

### ISSUE THREAD

**Issue by da-saiyam-shah** [vicmans/ng-toggle-button#53]
I am using this component in angular 15. 

Is there any property by which we can center align text? Currently, it is either left or right.

![image](https://github.com/vicmans/ng-toggle-button/assets/100556416/3349a6cd-c081-49dd-a4e8-157393c2d067)

![image](https://github.com/vicmans/ng-toggle-button/assets/100556416/4bceccc5-f444-4f33-b32c-0f4efb041ac3)

**Comment by vicmans** [comment]
There is no align text property but you can align text using CSS doing this:

Add to your component a class to apply this specific style:
```html
<ng-toggle
    ...
    class="center-text"
></ng-toggle>
```

In your style file, add the styles for the `ng-toggle-left` and `ng-toggle-right` elements to add width and alignment
```css
ng-toggle.center-text .ng-toggle-left {
    text-align: center;
    width: YOUR_WITH;
    left: 0!important;
}

ng-toggle.center-text .ng-toggle-right {
    text-align: center;
    width: YOUR_WITH;
    right: 0!important;
}
```

You can change the values of the CSS properties.
